apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-manager
  namespace: wazuh
spec:
  replicas: 1 # Only one master node can be set in Wazuh cluster
  selector:
    matchLabels:
      app: wazuh-manager
      node-type: master
  serviceName: wazuh-cluster
  template:
    metadata:
      labels:
        app: wazuh-manager
        node-type: master
      name: wazuh-manager
    spec:
      serviceAccountName: wazuh-service-account
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 101
      volumes:
        - name: tmp-config
          emptyDir: {}
        - name: wazuh-conf
          configMap:
            name: wazuh-conf
        - name: filebeat-conf
          configMap:
            name: filebeat-conf
        - name: certs
          secret:
            secretName: certs
        - name: wazuh-authd-pass
          secret:
            secretName: wazuh-authd-pass
        - name: wazuh-pvc
          persistentVolumeClaim:
            claimName: wazuh-pvc-local
      initContainers:
        - name: replace-env-vars
          # image: wazuh/wazuh-manager:4.5.1
          image: wazuh/wazuh-manager@sha256:43efe51901c276c2de760a2635931db828f842f0b4acb3f753d34abd609365d6
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 256Mi
          securityContext:
            privileged: false
            runAsNonRoot: false # Wazuh & Filebeat processes run with 0 UID .......
            # runAsUser: 1000
            # runAsGroup: 1000
            allowPrivilegeEscalation: false
            # readOnlyRootFilesystem : true
            capabilities:
              drop: ["ALL"]
          env: 
            - name: INDEXER_URL
              value: '["https://wazuh-indexer:9200"]'
            - name: INDEXER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: indexer-cred
                  key: username
            - name: INDEXER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: indexer-cred
                  key: password
            - name: WAZUH_CLUSTER_KEY
              valueFrom:
                secretKeyRef:
                  name: wazuh-cluster-key
                  key: key
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command:
            - /bin/sh
            - -ec
            - |
              cp /etc/filebeat/filebeat.yml /conf-manager/filebeat.yml
              cp /wazuh-config-mount/etc/ossec.conf /conf-manager/manager.conf

              ### Filebeat ###
              sed -i "s|\${INDEXER_URL}|$INDEXER_URL|g;
                      s|\${INDEXER_USERNAME}|$INDEXER_USERNAME|g;
                      s|\${INDEXER_PASSWORD}|$INDEXER_PASSWORD|g" /conf-manager/filebeat.yml

              ### Manager ###
              sed -i "s|\${NODE_NAME}|$NODE_NAME|g;
                      s|\${WAZUH_CLUSTER_KEY}|$WAZUH_CLUSTER_KEY|g" /conf-manager/manager.conf
          volumeMounts:
            - name: tmp-config
              mountPath: /conf-manager/
            - name: filebeat-conf
              mountPath: /etc/filebeat/filebeat.yml
              subPath: filebeat.yml
              readOnly: true
            - name: wazuh-conf
              mountPath: /wazuh-config-mount/etc/ossec.conf
              subPath: manager.conf
              readOnly: true
      containers:
        - name: wazuh-manager
          # image: wazuh/wazuh-manager:4.5.1
          image: wazuh/wazuh-manager@sha256:43efe51901c276c2de760a2635931db828f842f0b4acb3f753d34abd609365d6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1515
              name: registration
            - containerPort: 1516
              name: cluster
            - containerPort: 55000
              name: api
          # startupProbe: {}
          # livenessProbe: {}
          # readinessProbe: {}
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            privileged: false
            runAsNonRoot: false # Wazuh & Filebeat processes run with 0 UID .......
            # runAsUser: 1000
            # runAsGroup: 1000
            allowPrivilegeEscalation: false
            # readOnlyRootFilesystem : true
            capabilities:
              drop: ["ALL"] # "AUDIT_WRITE","MKNOD","SETFCAP","SETPCAP"
              add: ["CHOWN","DAC_OVERRIDE","FOWNER","FSETID","KILL","NET_BIND_SERVICE","SETGID","SETUID","SYS_CHROOT"]
          env:
            - name: API_USERNAME
              valueFrom:
                secretKeyRef:
                  name: wazuh-api-cred
                  key: username
            - name: API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wazuh-api-cred
                  key: password
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            # Conf
            - name: tmp-config
              mountPath: /wazuh-config-mount/etc/ossec.conf
              subPath: manager.conf
              readOnly: true
            # - name: wazuh-conf
            #   mountPath: /var/ossec/etc/local_internal_options.conf
            #   subPath: local_internal_options.conf
            #   readOnly: true
            - name: certs
              mountPath: /etc/ssl/root-ca.pem
              subPath: root-ca.pem
              readOnly: true
            - name: certs
              mountPath: /etc/ssl/filebeat.pem
              subPath: filebeat.pem
              readOnly: true
            - name: certs
              mountPath: /etc/ssl/filebeat.key
              subPath: filebeat.key
              readOnly: true
            - name: wazuh-authd-pass
              mountPath: /wazuh-config-mount/etc/authd.pass
              subPath: authd.pass
              readOnly: true
            - name: tmp-config
              mountPath: /etc/filebeat/filebeat.yml
              subPath: filebeat.yml
              readOnly: false
            - name: filebeat-conf
              mountPath: /usr/share/filebeat/module/wazuh/alerts/manifest.yml
              subPath: alerts_manifest.yml
              readOnly: false
            - name: filebeat-conf
              mountPath: /usr/share/filebeat/module/wazuh/archives/manifest.yml
              subPath: archives_manifest.yml
              readOnly: false
            - name: filebeat-conf
              mountPath: /usr/share/filebeat/module/wazuh/alerts/ingest/pipeline.json
              subPath: wazuh_alerts_pipeline.json
              readOnly: false
            - name: filebeat-conf
              mountPath: /etc/filebeat/wazuh-template.json
              subPath: wazuh-template.json
              readOnly: false
            # Data
            - name: wazuh-pvc
              mountPath: /var/ossec/api/configuration
              subPathExpr: $(NODE_NAME)/wazuh/var/ossec/api/configuration
              readOnly: false
            - name: wazuh-pvc
              mountPath: /var/ossec/etc
              subPathExpr: $(NODE_NAME)/wazuh/var/ossec/etc
              readOnly: false
            - name: wazuh-pvc
              mountPath: /var/ossec/logs
              subPathExpr: $(NODE_NAME)/wazuh/var/ossec/logs
              readOnly: false
            - name: wazuh-pvc
              mountPath: /var/ossec/queue
              subPathExpr: $(NODE_NAME)/wazuh/var/ossec/queue
              readOnly: false
            - name: wazuh-pvc
              mountPath: /var/ossec/var/multigroups
              subPathExpr: $(NODE_NAME)/wazuh/var/ossec/var/multigroups
              readOnly: false
            - name: wazuh-pvc
              mountPath: /var/ossec/integrations
              subPathExpr: $(NODE_NAME)/wazuh/var/ossec/integrations
              readOnly: false
            - name: wazuh-pvc
              mountPath: /var/ossec/active-response/bin
              subPathExpr: $(NODE_NAME)/wazuh/var/ossec/active-response/bin
              readOnly: false
            - name: wazuh-pvc
              mountPath: /var/ossec/agentless
              subPathExpr: $(NODE_NAME)/wazuh/var/ossec/agentless
              readOnly: false
            - name: wazuh-pvc
              mountPath: /var/ossec/wodles
              subPathExpr: $(NODE_NAME)/wazuh/var/ossec/wodles
              readOnly: false
            - name: wazuh-pvc
              mountPath: /etc/filebeat
              subPathExpr: $(NODE_NAME)/filebeat/etc/filebeat
              readOnly: false
            - name: wazuh-pvc
              mountPath: /var/lib/filebeat
              subPathExpr: $(NODE_NAME)/filebeat/var/lib/filebeat/
              readOnly: false