apiVersion: v1
kind: Service
metadata:
  name: wazuh-worker
  namespace: wazuh
  labels:
    app: wazuh-manager
spec:
  selector:
    app: wazuh-manager
    node-type: worker
  ports:
    - name: syslog-events
      port: 514
      targetPort: 514
    - name: agents-events
      port: 1514
      targetPort: 1514
  type: LoadBalancer