apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: wazuh
  name: role-configmaps
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
