apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wazuh
  labels:
    app: pv-wazuh
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /srv/pv_wazuh # Path in Minikube node, after /srv/ you need to create manualy your PV directory
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube