apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-pvc-local
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: pv-wazuh