apiVersion: v1
kind: Secret
metadata:
  name: indexer-cred-bcrypt
  namespace: wazuh
data:
  username: YWRtaW4= # string "admin" base64 encoded
  password: JDJhJDEyJEJ0NDNlRExES3dYa0pUdE1jRDRxa3UxUlZ3akdqQWJ5eTdtY0RMcTB5MUkyUEpOTW15ZUJt  
            # Bcrypt string of "SecretPassword" = $2a$12$Bt43eDLDKwXkJTtMcD4qku1RVwjGjAbyy7mcDLq0y1I2PJNMmyeBm and base64 encoded
            # Opensearch use bcrypt password to store password, you can convert your password on this site (for example) => https://bcrypt-generator.com/
            # Or use Opensearch container to execute this command (don't forgot to 'chmod +x' if needed) => plugins/opensearch-security/tools/hash.sh -p <new-password>