apiVersion: v1
kind: Secret
metadata:
  name: indexer-cred
  namespace: wazuh
data:
  username: YWRtaW4=              # string "admin" base64 encoded
  password: U2VjcmV0UGFzc3dvcmQ=  # string "SecretPassword" base64 encoded