apiVersion: v1
kind: Secret
metadata:
  name: wazuh-cluster-key
  namespace: wazuh
data:
  key: YTIzNzI2NGU2YjVhNjZhY2QwYzlkNWM1MmI4MWY3Njk= 
       # string "a237264e6b5a66acd0c9d5c52b81f769" base64 encoded
       # This key must be 32 characters long. You can execute => openssl rand -hex 16