apiVersion: v1
kind: Secret
metadata:
  name: wazuh-api-cred
  namespace: wazuh
data:
  username: d2F6dWgtYXBp          # string "wazuh-api" base64 encoded
  password: eiFCTDlBd3RtZz1GUUp2  # string "z!BL9Awtmg=FQJv" base64 encoded